# Generated by Django 5.2.17 on 2026-09-14 08:02

import datetime
import django.core.validators
import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=400)),
                ('state', models.CharField(choices=[('open', 'Новое'), ('requested', 'Запрошено пояснение'), ('accepted', 'Исключение подтверждено'), ('escalated', 'Руководителю'), ('resolved', 'Исправлено')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checkpoint', models.CharField(choices=[('13', '13:00'), ('17', '17:00'), ('close', 'Закрытие')], max_length=5)),
                ('available_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('first_received_at', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Постоянный код')),
                ('name', models.CharField(max_length=200, verbose_name='Адрес / название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('network', models.CharField(choices=[('MM', 'Мильстрим'), ('KK', 'Культура крепкого')], max_length=2, verbose_name='Сеть')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, validators=[reports.models.valid_timezone], verbose_name='Часовой пояс')),
                ('opens_at', models.TimeField(default=datetime.time(10, 0), verbose_name='Открытие')),
                ('closes_at', models.TimeField(default=datetime.time(22, 0), verbose_name='Закрытие')),
                ('weekdays', models.JSONField(default=reports.models.all_weekdays, validators=[reports.models.valid_weekdays], verbose_name='Рабочие дни (0–6)')),
                ('active_from', models.DateField(verbose_name='Начало работы в сервисе')),
                ('active_until', models.DateField(blank=True, null=True, verbose_name='Последний рабочий день')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['network', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('last_success', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FindingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='reports.finding')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reports.finding')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='reports.report'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipts', models.PositiveIntegerField()),
                ('units', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('request_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='reports.report')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Рабочая дата')),
                ('closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Открытие')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Закрытие')),
                ('reason', models.CharField(max_length=300, verbose_name='Причина')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.store')),
            ],
            options={
                'verbose_name': 'исключение графика',
                'verbose_name_plural': 'Исключения графика',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.store'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Рабочая дата')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='План выручки')),
                ('receipts', models.PositiveIntegerField(blank=True, null=True, verbose_name='План чеков (необязательно)')),
                ('units', models.PositiveIntegerField(blank=True, null=True, verbose_name='План алкогольных единиц')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=300, verbose_name='Основание / причина изменения')),
                ('approved_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.store')),
            ],
            options={
                'verbose_name': 'утверждённая версия плана',
                'verbose_name_plural': 'Версии планов',
                'ordering': ['-approved_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('store', 'Магазин'), ('office', 'Видеоконтроль'), ('manager', 'Руководитель')], max_length=16, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
                ('stores', models.ManyToManyField(blank=True, to='reports.store', verbose_name='Доступные магазины сотрудника')),
            ],
            options={
                'verbose_name': 'доступ сотрудника',
                'verbose_name_plural': 'Доступ сотрудников',
            },
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('report', 'version', 'kind'), name='unique_finding'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('report', 'version'), name='unique_revision'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_schedule_date'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['date', 'checkpoint'], name='reports_rep_date_834453_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('store', 'date', 'checkpoint'), name='unique_report'),
        ),
    ]
