# Generated by Django 5.2.17 on 2026-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='expected_through',
            field=models.DateField(editable=False, null=True),
        ),
    ]
