# Generated by Django 5.2.17 on 2026-09-14 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_store_expected_through'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('position', models.CharField(default='Продавец', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('source_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.TextField(blank=True)),
                ('checksum', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stats', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='origin',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='plan',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='units_per_receipt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='revision',
            name='employee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='revision',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='origin',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='revision',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='store',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='monitoring_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='receipts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='received_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.store')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=250)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('values', models.JSONField(default=list)),
                ('formulas', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='reports.sourcedocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'title'), name='unique_source_sheet')],
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='reports.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='reports.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'slot'), name='unique_store_staff_slot')],
            },
        ),
    ]
