# Generated by Django 5.2.17 on 2026-09-14 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_employee_legalentity_sourcedocument_plan_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='План выручки'),
        ),
    ]
