# Generated by Django 5.2.17 on 2026-09-14 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_plan_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('channel', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('next_send_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.findingaction'),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], default='telegram', max_length=12),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(default='created', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.finding'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('finding', 'channel', 'event_key'), name='unique_notification_event'),
        ),
    ]
