# Generated by Django 5.2.17 on 2026-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_employee_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Основание / причина изменения'),
        ),
    ]
