async (page) => {
  const output = 'output/playwright/';
  await page.getByRole('button', {name:'Закрытие', exact:true}).click();
  await page.getByRole('button', {name:'Требуют внимания', exact:true}).click();
  await page.getByRole('button', {name:'Обновить данные',exact:true}).click();
  await page.getByRole('button', {name:'УЧ-03, Закрытие: Не полностью',exact:true}).waitFor();
  const main=page.locator('.w-main');
  const top=await main.locator('.w-page-head').boundingBox();
  const panel=await page.locator('.w-table-panel').boundingBox();
  await page.screenshot({path:output+'office-daily-v2.png',clip:{x:top.x,y:top.y,width:panel.width,height:Math.min(1030,panel.y+panel.height-top.y)}});
  await page.getByRole('button', {name:'УЧ-03, Закрытие: Не полностью',exact:true}).click();
  const dialog=page.getByRole('dialog');
  if (!(await dialog.innerText()).includes('не заполнены алкогольные единицы')) throw new Error('Missing explanation');
  await dialog.getByRole('button',{name:'Задать вопрос магазину',exact:true}).click();
  await dialog.getByRole('textbox',{name:'Вопрос магазину',exact:true}).fill('Уточните количество алкогольных единиц на закрытие');
  await dialog.screenshot({path:output+'office-question-v2.png'});
  await dialog.getByRole('button',{name:'Сохранить вопрос',exact:true}).click();
  await dialog.getByText('Вопрос от видеоконтроля',{exact:true}).waitFor();
  const question=dialog.locator('.w-finding').filter({hasText:'Вопрос от видеоконтроля'});
  await question.screenshot({path:output+'office-question-thread.png'});
  await dialog.getByRole('button',{name:'Закрыть отчёт',exact:true}).click();
  await page.getByRole('link',{name:'Управление',exact:true}).click();
  await page.getByRole('button',{name:'Сотрудники',exact:true}).click();
  await page.getByRole('button',{name:'Добавить сотрудника',exact:true}).click();
  await page.getByRole('dialog').getByRole('textbox',{name:'ФИО',exact:true}).fill('Новикова Мария');
  await page.getByRole('dialog').screenshot({path:output+'office-employee-v2.png'});
  await page.getByRole('button',{name:'Отмена',exact:true}).click();
  await page.getByRole('button',{name:'Магазины',exact:true}).click();
  await page.getByRole('button',{name:'Изменить магазин УЧ-01',exact:true}).click();
  const team=page.getByRole('dialog').locator('.m-form-grid').nth(1);
  const fields=team.locator('label').filter({hasText:/Продавец [12]/});
  const a=await fields.first().boundingBox(), b=await fields.last().boundingBox();
  await page.screenshot({path:output+'office-team-row-v2.png',clip:{x:a.x,y:a.y,width:b.x+b.width-a.x,height:Math.max(a.height,b.height)}});
  await page.getByRole('dialog').evaluate(el=>el.scrollTop=el.scrollHeight);
  const heading=await page.getByRole('heading',{name:'График и контроль сроков',exact:true}).boundingBox();
  const footer=await page.getByRole('dialog').locator('form>footer').boundingBox();
  await page.screenshot({path:output+'office-schedule-v2.png',clip:{x:footer.x+18,y:heading.y-6,width:footer.width-36,height:footer.y+footer.height-heading.y+6}});
  await page.getByRole('button',{name:'Отмена',exact:true}).click();
  await page.getByRole('button',{name:'Планы',exact:true}).click();
  await page.getByRole('button',{name:'Изменить план УЧ-01',exact:true}).click();
  await page.getByRole('dialog').getByLabel('Основание / причина изменения').fill('План на рабочий день');
  await page.getByRole('dialog').locator('.m-form-grid').screenshot({path:output+'office-plan-fields-v2.png'});
  await page.getByRole('button',{name:'Отмена',exact:true}).click();
  await page.getByRole('button',{name:'Уведомления',exact:true}).click();
  await page.locator('.m-notification-grid').screenshot({path:output+'office-notifications.png'});
  return {questionSaved:true, screenshots:8};
}
